rush-02 : main.o check.o print.o string.o translate.o
	gcc -o rush-02 main.o check.o print.o string.o translate.o

main.o : main.c
	gcc -o main.o -c main.c

check.o : check.c
	gcc -o check.o -c check.c

print.o : print.c
	gcc -o print.o -c print.c

string.o : string.c
	gcc -o string.o -c string.c

translate.o : translate.c
	gcc -o translate.o -c translate.c
